# Site settings
title: North American High-Tech Investment
email: info (at) nahtinvest.com
description: > North American High-Tech Investment # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "nahtinvest.com" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
